### ISSUE TITLE
api error

### ISSUE THREAD

**Issue by itnygr2** [dtolnay/star-history#7]
```
➜  ~ star-history rust-lang/rust
Error: error sending request for url (https://api.github.com/graphql): error trying to connect: unexpected EOF

Caused by:
    0: error trying to connect: unexpected EOF
    1: unexpected EOF
```

**Comment by dtolnay** [comment]
I can't tell what happened here. But the same invocation works on my machine.

If anyone ends up reproducing this and can look into it, I would be happy to accept a PR to eliminate this failure mode.
